<?php
include('layouts/header.php');
?>
<section class="container mt-auto">
    <div>
        <img src="images/layered-peaks-haikei (2).png" width="1300" max-height="400" alt="">
    </div>
    <div class="mt-5">


        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat ullam debitis nesciunt. Iusto expedita maiores nihil, iste voluptas optio ipsa quidem. Officia, perspiciatis atque. Quas, ex beatae quisquam inventore, corrupti accusamus ducimus et non veniam itaque recusandae adipisci ab. Dolore, atque molestiae beatae deserunt odit culpa minima cumque repellat, ullam consequatur nulla sint labore. Magnam harum sed pariatur odit consequatur reiciendis optio distinctio repellat? Tempora perferendis, dolorum ex qui aperiam repellendus non voluptas debitis aspernatur sapiente nulla consequatur nam dolorem modi odit reiciendis unde iste corrupti rerum animi quis cum atque aut praesentium. Rerum beatae obcaecati magnam eveniet earum libero.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat ullam debitis nesciunt. Iusto expedita maiores nihil, iste voluptas optio ipsa quidem. Officia, perspiciatis atque. Quas, ex beatae quisquam inventore, corrupti accusamus ducimus et non veniam itaque recusandae adipisci ab. Dolore, atque molestiae beatae deserunt odit culpa minima cumque repellat, ullam consequatur nulla sint labore. Magnam harum sed pariatur odit consequatur reiciendis optio distinctio repellat? Tempora perferendis, dolorum ex qui aperiam repellendus non voluptas debitis aspernatur sapiente nulla consequatur nam dolorem modi odit reiciendis unde iste corrupti rerum animi quis cum atque aut praesentium. Rerum beatae obcaecati magnam eveniet earum libero.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat ullam debitis nesciunt. Iusto expedita maiores nihil, iste voluptas optio ipsa quidem. Officia, perspiciatis atque. Quas, ex beatae quisquam inventore, corrupti accusamus ducimus et non veniam itaque recusandae adipisci ab. Dolore, atque molestiae beatae deserunt odit culpa minima cumque repellat, ullam consequatur nulla sint labore. Magnam harum sed pariatur odit consequatur reiciendis optio distinctio repellat? Tempora perferendis, dolorum ex qui aperiam repellendus non voluptas debitis aspernatur sapiente nulla consequatur nam dolorem modi odit reiciendis unde iste corrupti rerum animi quis cum atque aut praesentium. Rerum beatae obcaecati magnam eveniet earum libero.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat ullam debitis nesciunt. Iusto expedita maiores nihil, iste voluptas optio ipsa quidem. Officia, perspiciatis atque. Quas, ex beatae quisquam inventore, corrupti accusamus ducimus et non veniam itaque recusandae adipisci ab. Dolore, atque molestiae beatae deserunt odit culpa minima cumque repellat, ullam consequatur nulla sint labore. Magnam harum sed pariatur odit consequatur reiciendis optio distinctio repellat? Tempora perferendis, dolorum ex qui aperiam repellendus non voluptas debitis aspernatur sapiente nulla consequatur nam dolorem modi odit reiciendis unde iste corrupti rerum animi quis cum atque aut praesentium. Rerum beatae obcaecati magnam eveniet earum libero.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat ullam debitis nesciunt. Iusto expedita maiores nihil, iste voluptas optio ipsa quidem. Officia, perspiciatis atque. Quas, ex beatae quisquam inventore, corrupti accusamus ducimus et non veniam itaque recusandae adipisci ab. Dolore, atque molestiae beatae deserunt odit culpa minima cumque repellat, ullam consequatur nulla sint labore. Magnam harum sed pariatur odit consequatur reiciendis optio distinctio repellat? Tempora perferendis, dolorum ex qui aperiam repellendus non voluptas debitis aspernatur sapiente nulla consequatur nam dolorem modi odit reiciendis unde iste corrupti rerum animi quis cum atque aut praesentium. Rerum beatae obcaecati magnam eveniet earum libero.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat ullam debitis nesciunt. Iusto expedita maiores nihil, iste voluptas optio ipsa quidem. Officia, perspiciatis atque. Quas, ex beatae quisquam inventore, corrupti accusamus ducimus et non veniam itaque recusandae adipisci ab. Dolore, atque molestiae beatae deserunt odit culpa minima cumque repellat, ullam consequatur nulla sint labore. Magnam harum sed pariatur odit consequatur reiciendis optio distinctio repellat? Tempora perferendis, dolorum ex qui aperiam repellendus non voluptas debitis aspernatur sapiente nulla consequatur nam dolorem modi odit reiciendis unde iste corrupti rerum animi quis cum atque aut praesentium. Rerum beatae obcaecati magnam eveniet earum libero.</p>
    </div>
</section>

<?php
include('layouts/footer.php');
?>